add ocean node logs

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -155,7 +155,7 @@ jobs:
         run: |
           npm ci
           npm run build
-          npm run start &
+          npm run start > ocean-node.log 2>&1 &
         env:
           PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
           IPFS_GATEWAY: http://172.15.0.16:8080/
@@ -192,6 +192,13 @@ jobs:
           INDEXING_RETRY_INTERVAL: 4000
           INDEXING_MAX_RETRIES: 120
           OCEAN_NODE_URL: 'http://127.0.0.1:8001'
+
+      - name: Print Ocean Node Logs if tests fail
+        if: ${{ failure() }}
+        run: |
+          echo "========== Ocean Node Logs =========="
+          cat ${{ github.workspace }}/ocean-node/ocean-node.log || echo "Log file not found"
+
       - name: Upload coverage
         uses: actions/upload-artifact@v4
         with:
