show last lines first

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -197,8 +197,7 @@ jobs:
         if: ${{ failure() }}
         run: |
           echo "========== Ocean Node Logs =========="
-          cat ${{ github.workspace }}/ocean-node/ocean-node.log || echo "Log file not found"
-
+          tac ${{ github.workspace }}/ocean-node/ocean-node.log || echo "Log file not found"
       - name: Upload coverage
         uses: actions/upload-artifact@v4
         with:
